//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Survey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OriginalAnswer
    {
        public int Id { get; set; }
        public string Answer_text { get; set; }
        public int Question_id { get; set; }
        public bool Is_deleted { get; set; }
    
        public virtual Question Question { get; set; }
    }
}
